schema_version = "1.0.0"

id = "MakePlanarFacesPlus"
version = "1.0.3"
name = "Make Planar Faces Plus"
tagline = "Powerful Make Planar Faces Operator"
maintainer = "Anton Florey <anton.florey@googlemail.com>"
type = "add-on"
website = "https://github.com/AntonFlorey/MakePlanarFacesPlus"
tags = ["Mesh"]
blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

platforms = ["windows-x64", "linux-x64", "macos-arm64", "macos-x64"]

