schema_version = "1.0.0"

id = "MakePlanarFacesPlus"
version = "1.0.1"
name = "Make Planar Faces Plus"
tagline = "Powerful Make Planar Faces Operator"
maintainer = "Anton Florey <anton.florey@googlemail.com>"
type = "add-on"
website = "https://github.com/AntonFlorey/MakePlanarFacesPlus"
tags = ["Mesh"]
blender_version_min = "4.4.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

platforms = ["windows-x64"]

wheels = [
  "./wheels/mpfp-1.0.0-cp311-cp311-win_amd64.whl",
]
